---
    name: CI

    'on':
      push:
        branches: [main]
      pull_request:
        branches: [main]

    jobs:

      CI:
        strategy:
          matrix:
            runner: [macos-14]
        runs-on: ${{ matrix.runner }}
        steps:
          - uses: actions/checkout@v4
          - uses: ruby/setup-ruby@v1
            with:
              bundler-cache: true

          - name: Install python
            run: brew install python@3.8

          - name: Build
            run: ./build.sh
